FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y maven docker.io && \
    rm -rf /var/lib/apt/lists/*

RUN git config --system --add safe.directory '*'

RUN usermod -aG docker jenkins

USER jenkins
